import postgres from 'npm:postgres@3.4.7'
const sql=postgres(Deno.env.get('SUPABASE_DB_URL')!,{ssl:'require',prepare:false,max:1,idle_timeout:20,connect_timeout:10})
const TZ='America/Los_Angeles'
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type,x-pepper-session','Access-Control-Allow-Methods':'POST,OPTIONS','Cache-Control':'no-store','Content-Type':'application/json; charset=utf-8'}
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
function dateLA(d=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}
function addDays(date:string,n:number){const [y,m,d]=date.split('-').map(Number),x=new Date(Date.UTC(y,m-1,d+n));return x.toISOString().slice(0,10)}
function localDate(ts:string){return new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(ts))}
function dayLabel(date:string){const d=new Date(date+'T12:00:00Z');return new Intl.DateTimeFormat('en-US',{timeZone:'UTC',weekday:'short',month:'short',day:'numeric'}).format(d)}
function timeLabel(ts:string){return new Intl.DateTimeFormat('en-US',{timeZone:TZ,hour:'numeric',minute:'2-digit'}).format(new Date(ts))}
function transportRelevant(x:any){if(!x)return false;if(['school_dropoff','school_pickup'].includes(x.kind))return true;if(x.kind!=='transport')return false;if(x.person_slug)return true;const text=`${x.title||''} ${x.location||''}`.toLowerCase();return /(pickup|pick up|dropoff|drop off|ride|driver|carpool|transport)/.test(text)}
async function member(req:Request){const token=req.headers.get('x-pepper-session')||'';if(!UUID.test(token))return null;const rows=await sql<any[]>`select m.id,m.household_id,m.slug,m.display_name,m.role from public.member_sessions s join public.household_members m on m.id=s.member_id where s.token=${token}::uuid and s.revoked_at is null and s.expires_at>now() limit 1`;return rows[0]||null}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});if(req.method!=='POST')return new Response(JSON.stringify({error:'Method not allowed'}),{status:405,headers:cors});try{const m=await member(req);if(!m)return new Response(JSON.stringify({error:'Pepper session required.'}),{status:401,headers:cors});const start=dateLA(),end7=addDays(start,6),end30=addDays(start,30);const [events,routines,tasks,calendar,members,consequences,watch]=await Promise.all([
sql<any[]>`select id,title,person_slug,starts_at,ends_at,location,status,visibility,owner_member_id,kind,transport_owner_member_id,transport_status,source,adult_required,adult_requirement_label,adult_owner_member_id,adult_requirement_status from public.events where household_id=${m.household_id}::uuid and status<>'canceled' and starts_at >= (${start}::date::timestamp at time zone ${TZ}) and starts_at < ((${end30}::date + 1)::timestamp at time zone ${TZ}) and (visibility='household' or owner_member_id=${m.id}::uuid) order by starts_at`,
sql<any[]>`select r.id,r.title,r.person_slug,r.location,r.kind,r.transport_owner_member_id,r.importance,r.days_of_week,r.starts_local::text,r.ends_local::text,r.effective_start,r.effective_end,gs::date::text occurrence_date,((gs::date+r.starts_local) at time zone ${TZ}) starts_at,case when r.ends_local is null then null else ((gs::date+r.ends_local) at time zone ${TZ}) end ends_at from private.family_routines r cross join generate_series(${start}::date,${end30}::date,interval '1 day') gs where r.household_id=${m.household_id}::uuid and r.active=true and extract(dow from gs)::int=any(r.days_of_week) and (r.effective_start is null or gs::date>=r.effective_start) and (r.effective_end is null or gs::date<=r.effective_end) order by starts_at`,
sql<any[]>`select id,title,owner_member_id,visibility,status,due_at,source from public.tasks where household_id=${m.household_id}::uuid and status not in ('completed','canceled') and due_at is not null and due_at >= (${start}::date::timestamp at time zone ${TZ}) and due_at < ((${end30}::date + 1)::timestamp at time zone ${TZ}) and (visibility='household' or owner_member_id=${m.id}::uuid) order by due_at`,
sql<any[]>`select calendar_name,status,sync_status,scan_window_days,last_attempt_at,last_synced_at,last_error from public.calendar_connections where household_id=${m.household_id}::uuid and provider='google' limit 1`,
sql<any[]>`select id,slug,display_name from public.household_members where household_id=${m.household_id}::uuid`,
sql<any[]>`select c.id,c.consequence_type,c.title,c.summary,c.severity,c.status,c.event_id,c.affected_member_id,c.detected_at,c.last_seen_at,e.starts_at event_starts_at from public.consequences c left join public.events e on e.id=c.event_id where c.household_id=${m.household_id}::uuid and c.status='open' order by case c.severity when 'urgent' then 0 when 'needs_attention' then 1 else 2 end,c.last_seen_at desc`,
sql<any[]>`select id,title,person_slug,category,starts_on::text,ends_on::text,status,preparation_required,preparation_summary,prep_lead_days,owner_member_id,visibility,source,source_ref,confidence from private.future_watch_items where household_id=${m.household_id}::uuid and status not in ('canceled','completed') and starts_on between ${start}::date and ${end30}::date and (visibility='household' or owner_member_id=${m.id}::uuid) order by starts_on`
]);
const memberName=(id:string|null)=>members.find((x:any)=>x.id===id)?.display_name||null
const actual=(events||[]).map((e:any)=>({...e,item_type:'event',date:localDate(e.starts_at),transport_owner_name:memberName(e.transport_owner_member_id)}))
const routineItems=(routines||[]).map((r:any)=>({id:`routine:${r.id}:${r.occurrence_date}`,routine_id:r.id,title:r.title,person_slug:r.person_slug,starts_at:r.starts_at,ends_at:r.ends_at,location:r.location,status:'confirmed',visibility:'household',kind:r.kind,transport_owner_member_id:r.transport_owner_member_id,transport_owner_name:memberName(r.transport_owner_member_id),source:'routine',importance:r.importance,item_type:'routine',date:r.occurrence_date}))
const watchItems=(watch||[]).map((w:any)=>({...w,item_type:'watch',date:w.starts_on,owner_name:memberName(w.owner_member_id),prep_on:w.preparation_required&&w.prep_lead_days>0?addDays(w.starts_on,-w.prep_lead_days):w.starts_on}))
const combined=[...actual,...routineItems].sort((a:any,b:any)=>+new Date(a.starts_at)-+new Date(b.starts_at))
const weekItems=combined.filter((x:any)=>x.date<=end7),aheadItems=actual.filter((x:any)=>x.date>end7)
const weekWatch=watchItems.filter((x:any)=>x.date<=end7),aheadWatch=watchItems.filter((x:any)=>x.date>end7)
const weekTasks=(tasks||[]).filter((t:any)=>localDate(t.due_at)<=end7).map((t:any)=>({...t,date:localDate(t.due_at),owner_name:memberName(t.owner_member_id)}))
const aheadTasks=(tasks||[]).filter((t:any)=>localDate(t.due_at)>end7).map((t:any)=>({...t,date:localDate(t.due_at),owner_name:memberName(t.owner_member_id)}))
const routineMap=new Map<string,any>();for(const r of routines||[]){if(r.occurrence_date<=end7||routineMap.has(r.id))continue;routineMap.set(r.id,{id:r.id,title:r.title,person_slug:r.person_slug,location:r.location,kind:r.kind,transport_owner_member_id:r.transport_owner_member_id,transport_owner_name:memberName(r.transport_owner_member_id),days_of_week:r.days_of_week,starts_local:r.starts_local,importance:r.importance,summary:`${r.title} continues on its normal schedule${r.transport_owner_member_id?' · '+memberName(r.transport_owner_member_id)+' owns it':''}.`})}
const routineSummaries=[...routineMap.values()]
const days=[] as any[];for(let i=0;i<7;i++){const date=addDays(start,i);days.push({date,label:dayLabel(date),items:weekItems.filter((x:any)=>x.date===date),tasks:weekTasks.filter((x:any)=>x.date===date),watch:weekWatch.filter((x:any)=>x.date===date)})}
const readiness:any[]=[];for(const x of weekItems){if(transportRelevant(x)&&!x.transport_owner_member_id)readiness.push({type:'transport',severity:'needs_attention',date:x.date,title:x.title,summary:`${x.title}${x.starts_at?' · '+timeLabel(x.starts_at):''} needs a driver.`});if(x.adult_required&&!x.adult_owner_member_id)readiness.push({type:'adult_required',severity:'needs_attention',date:x.date,title:x.title,summary:`${x.title}${x.starts_at?' · '+timeLabel(x.starts_at):''} needs an adult assigned.`})}
for(const t of weekTasks){readiness.push({type:'due_task',severity:'prepare',date:t.date,title:t.title,summary:`Due ${dayLabel(t.date)}${t.owner_name?' · '+t.owner_name:''}.`})}
for(const w of watchItems){if(w.preparation_required&&w.prep_on<=end7){readiness.push({type:'future_prepare',severity:'prepare',date:w.prep_on,title:w.title,summary:w.preparation_summary||`Prepare for ${w.title} before ${dayLabel(w.starts_on)}.`})}}
const conflictTypes=new Set(['person_conflict','driver_conflict']);for(const c of consequences||[]){if(!conflictTypes.has(c.consequence_type))continue;const cDate=c.event_starts_at?localDate(c.event_starts_at):null;if(cDate&&cDate<=end7)readiness.push({type:'consequence',severity:c.severity,date:cDate,title:c.title,summary:c.summary})}
const cal=calendar[0]||null,connected=cal?.status==='connected',coordProblems=readiness.filter(x=>x.severity==='urgent'||x.severity==='needs_attention').length
const knownWeek=weekItems.length+weekWatch.length
const coverage={calendar_connected:connected,calendar_name:cal?.calendar_name||null,sync_status:cal?.sync_status||'never',last_synced_at:cal?.last_synced_at||null,scan_window_days:cal?.scan_window_days||14,known_week_items:knownWeek,due_week_tasks:weekTasks.length,future_watch_week:weekWatch.length,coordination_issues:coordProblems,headline:connected?(coordProblems?`Pepper sees ${coordProblems} coordination ${coordProblems===1?'issue':'issues'} to solve in the next seven days.`:`The next seven days look covered from the calendar and family state Pepper currently knows.`):`Pepper has ${knownWeek} known plans for the next seven days. Connect Google Calendar to make this view more complete.`}
const aheadConsequences=(consequences||[]).filter((c:any)=>conflictTypes.has(c.consequence_type)&&c.event_starts_at&&localDate(c.event_starts_at)>end7&&localDate(c.event_starts_at)<=end30).map((c:any)=>({type:'consequence',date:localDate(c.event_starts_at),title:c.title,when:dayLabel(localDate(c.event_starts_at)),category:'coordination',preparation_required:true,preparation_summary:c.summary}))
const futureWatch=[...aheadWatch.map((w:any)=>({type:'watch',date:w.date,title:w.title,when:dayLabel(w.date),category:w.category,preparation_required:w.preparation_required,preparation_summary:w.preparation_summary||null,prep_on:w.prep_on,owner_name:w.owner_name||null})),...aheadConsequences,...aheadItems.map((x:any)=>({type:'event',date:x.date,title:x.title,when:`${dayLabel(x.date)} · ${timeLabel(x.starts_at)}`,location:x.location||null})),...aheadTasks.map((t:any)=>({type:'task',date:t.date,title:t.title,when:`Due ${dayLabel(t.date)}`,owner_name:t.owner_name||null}))].sort((a:any,b:any)=>a.date.localeCompare(b.date)).slice(0,30)
return new Response(JSON.stringify({ok:true,start_date:start,end7_date:end7,end30_date:end30,coverage,calendar:cal,days,ahead:{items:aheadItems.slice(0,20),tasks:aheadTasks.slice(0,12),watch:aheadWatch,routine_summaries:routineSummaries,future_watch:futureWatch},readiness}),{headers:cors})
}catch(e){console.error(e);return new Response(JSON.stringify({error:e instanceof Error?e.message:'Pepper could not build the planning horizon.'}),{status:500,headers:cors})}})
