-- Preview-only reconstruction of runtime objects whose original production DDL
-- predates the captured V6 migration history. Never apply this file to production.

create schema if not exists private;
create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

alter table public.household_members
  add column if not exists pin_hash text;

create table if not exists public.member_sessions (
  token uuid primary key default gen_random_uuid(),
  member_id uuid not null references public.household_members(id) on delete cascade,
  device_label text,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '30 days'),
  revoked_at timestamptz
);

create index if not exists member_sessions_member_expiry_idx
  on public.member_sessions(member_id, expires_at desc);

create table if not exists private.pepper_login_attempts (
  id bigint generated by default as identity primary key,
  attempt_key text not null,
  succeeded boolean not null default false,
  attempted_at timestamptz not null default now()
);

create index if not exists pepper_login_attempts_key_time_idx
  on private.pepper_login_attempts(attempt_key, attempted_at desc);

create or replace function private.pepper_current_member_id()
returns uuid
language plpgsql
stable
security definer
set search_path to public, private, pg_temp
as $$
declare
  token_text text;
  member_result uuid;
begin
  token_text := current_setting('app.pepper_session_token', true);
  if token_text is null
     or token_text !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' then
    return null;
  end if;

  select s.member_id into member_result
  from public.member_sessions s
  where s.token = token_text::uuid
    and s.revoked_at is null
    and s.expires_at > now()
  limit 1;

  return member_result;
end;
$$;

create or replace function private.pepper_current_household_id()
returns uuid
language sql
stable
security definer
set search_path to public, private, pg_temp
as $$
  select m.household_id
  from public.household_members m
  where m.id = private.pepper_current_member_id()
  limit 1;
$$;

create or replace function private.pepper_current_role()
returns text
language sql
stable
security definer
set search_path to public, private, pg_temp
as $$
  select m.role
  from public.household_members m
  where m.id = private.pepper_current_member_id()
  limit 1;
$$;

create or replace function private.pepper_current_slug()
returns text
language sql
stable
security definer
set search_path to public, private, pg_temp
as $$
  select m.slug
  from public.household_members m
  where m.id = private.pepper_current_member_id()
  limit 1;
$$;

create or replace function private.pepper_set_session(session_token_input uuid)
returns uuid
language plpgsql
set search_path to public, private, pg_temp
as $$
declare
  member_result uuid;
begin
  perform set_config('app.pepper_session_token', session_token_input::text, true);
  member_result := private.pepper_current_member_id();
  if member_result is null then
    raise exception 'Pepper session expired. Please unlock Pepper again.' using errcode = '28000';
  end if;
  return member_result;
end;
$$;

create or replace function private.pepper_touch_session(session_token_input uuid)
returns void
language sql
security definer
set search_path to public, private, pg_temp
as $$
  update public.member_sessions
  set last_seen_at = now()
  where token = session_token_input
    and revoked_at is null
    and expires_at > now();
$$;

create or replace function private.pepper_end_session(session_token_input uuid)
returns void
language sql
security definer
set search_path to public, private, pg_temp
as $$
  update public.member_sessions
  set revoked_at = now(), last_seen_at = now()
  where token = session_token_input
    and revoked_at is null;
$$;

create or replace function private.pepper_start_session(
  household_slug_input text,
  member_slug_input text,
  pin_input text,
  device_label_input text default null
)
returns jsonb
language plpgsql
security definer
set search_path to public, private, extensions, pg_temp
as $$
declare
  member_row record;
  attempt_key_value text;
  recent_failures integer;
  new_token uuid;
  new_expiry timestamptz;
begin
  attempt_key_value := lower(left(trim(coalesce(household_slug_input, '')), 80))
    || ':' || lower(left(trim(coalesce(member_slug_input, '')), 80));

  delete from private.pepper_login_attempts
  where attempted_at < now() - interval '24 hours';
  delete from public.member_sessions
  where expires_at < now() - interval '7 days'
     or revoked_at < now() - interval '7 days';

  select count(*)::integer into recent_failures
  from private.pepper_login_attempts
  where attempt_key = attempt_key_value
    and succeeded = false
    and attempted_at > now() - interval '15 minutes';

  if recent_failures >= 5 then
    return jsonb_build_object(
      'ok', false,
      'error', 'Too many attempts. Wait 15 minutes and try again.',
      'retry_after_seconds', 900
    );
  end if;

  select m.id, m.household_id, m.slug, m.display_name, m.role, m.pin_hash,
    h.name as household_name, h.slug as household_slug
  into member_row
  from public.households h
  join public.household_members m on m.household_id = h.id
  where lower(h.slug) = lower(trim(coalesce(household_slug_input, '')))
    and lower(m.slug) = lower(trim(coalesce(member_slug_input, '')))
  limit 1;

  if not found
     or pin_input is null
     or pin_input !~ '^[0-9]{4,12}$'
     or member_row.pin_hash is null
     or member_row.pin_hash <> crypt(pin_input, member_row.pin_hash) then
    insert into private.pepper_login_attempts(attempt_key, succeeded)
    values (attempt_key_value, false);
    perform pg_sleep(0.35);
    return jsonb_build_object('ok', false, 'error', 'That name or PIN did not match.');
  end if;

  delete from private.pepper_login_attempts where attempt_key = attempt_key_value;

  new_token := gen_random_uuid();
  new_expiry := now() + interval '30 days';
  insert into public.member_sessions(
    token, member_id, device_label, last_seen_at, created_at, expires_at, revoked_at
  ) values (
    new_token, member_row.id, left(nullif(trim(device_label_input), ''), 120),
    now(), now(), new_expiry, null
  );

  return jsonb_build_object(
    'ok', true,
    'token', new_token,
    'expires_at', new_expiry,
    'member', jsonb_build_object(
      'id', member_row.id,
      'slug', member_row.slug,
      'display_name', member_row.display_name,
      'role', member_row.role
    ),
    'household', jsonb_build_object(
      'id', member_row.household_id,
      'slug', member_row.household_slug,
      'name', member_row.household_name
    )
  );
end;
$$;

create or replace function public.pepper_start_family_session(
  member_slug_input text,
  pin_input text,
  device_label_input text default null
)
returns jsonb
language sql
security invoker
set search_path to public, private, pg_temp
as $$
  select private.pepper_start_session(
    'eriksen', member_slug_input, pin_input, device_label_input
  );
$$;

alter table public.member_sessions enable row level security;
alter table private.pepper_login_attempts enable row level security;

revoke all on table public.member_sessions from public, anon, authenticated;
revoke all on table private.pepper_login_attempts from public, anon, authenticated;
grant all on table public.member_sessions to service_role;

revoke execute on function public.pepper_start_family_session(text, text, text) from public;
grant execute on function public.pepper_start_family_session(text, text, text) to anon, authenticated;

create table if not exists public.calendar_connections (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households(id) on delete cascade,
  connected_by_member_id uuid not null references public.household_members(id) on delete restrict,
  provider text not null default 'google',
  provider_calendar_id text not null default 'primary',
  calendar_name text,
  calendar_time_zone text,
  access_scope text not null default 'calendar.readonly',
  status text not null default 'disconnected' check (status in ('disconnected','connected','error')),
  sync_status text not null default 'never' check (sync_status in ('never','syncing','healthy','error')),
  scan_window_days integer not null default 14 check (scan_window_days between 7 and 14),
  last_attempt_at timestamptz,
  last_synced_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(household_id, provider)
);

create table if not exists private.calendar_oauth_states (
  id uuid primary key default gen_random_uuid(),
  state_hash text unique not null,
  code_verifier text not null,
  household_id uuid not null references public.households(id) on delete cascade,
  member_id uuid not null references public.household_members(id) on delete cascade,
  expires_at timestamptz not null,
  consumed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists private.calendar_tokens (
  connection_id uuid primary key references public.calendar_connections(id) on delete cascade,
  vault_secret_id uuid not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists private.calendar_sync_runs (
  id bigint generated by default as identity primary key,
  connection_id uuid not null references public.calendar_connections(id) on delete cascade,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null default 'running' check (status in ('running','healthy','error')),
  events_seen integer not null default 0,
  events_upserted integer not null default 0,
  duplicates_merged integer not null default 0,
  events_removed integer not null default 0,
  error_code text,
  error_message text
);

alter table public.calendar_connections enable row level security;
alter table private.calendar_oauth_states enable row level security;
alter table private.calendar_tokens enable row level security;
alter table private.calendar_sync_runs enable row level security;

revoke all on table public.calendar_connections from public, anon, authenticated;
revoke all on table private.calendar_oauth_states from public, anon, authenticated;
revoke all on table private.calendar_tokens from public, anon, authenticated;
revoke all on table private.calendar_sync_runs from public, anon, authenticated;
grant all on table public.calendar_connections to service_role;

create table if not exists public.integration_connections (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households(id) on delete cascade,
  member_id uuid references public.household_members(id) on delete cascade,
  provider text not null check (provider in ('gmail','apple_health')),
  status text not null default 'disconnected' check (status in ('disconnected','pending','connected','error')),
  access_scope text not null default '',
  last_attempt_at timestamptz,
  last_synced_at timestamptz,
  last_error text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique nulls not distinct (household_id, member_id, provider)
);

create table if not exists public.health_daily_metrics (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households(id) on delete cascade,
  member_id uuid not null references public.household_members(id) on delete cascade,
  metric_date date not null,
  step_count integer check (step_count is null or step_count >= 0),
  step_goal integer check (step_goal is null or step_goal > 0),
  active_minutes integer check (active_minutes is null or active_minutes >= 0),
  source text not null default 'apple_health',
  source_updated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(member_id, metric_date, source)
);

create table if not exists private.health_ingest_tokens (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households(id) on delete cascade,
  member_id uuid not null references public.household_members(id) on delete cascade,
  token_hash text unique not null,
  label text not null default 'iPhone HealthKit',
  expires_at timestamptz,
  revoked_at timestamptz,
  last_used_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.integration_connections enable row level security;
alter table public.health_daily_metrics enable row level security;
alter table private.health_ingest_tokens enable row level security;

revoke all on table public.integration_connections from public, anon, authenticated;
revoke all on table public.health_daily_metrics from public, anon, authenticated;
revoke all on table private.health_ingest_tokens from public, anon, authenticated;
grant all on table public.integration_connections to service_role;
grant all on table public.health_daily_metrics to service_role;
