create table if not exists public.locations (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households(id) on delete cascade,
  name text not null,
  address text,
  kind text not null default 'place',
  latitude double precision,
  longitude double precision,
  source text not null default 'pepper',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (household_id, name)
);

create table if not exists public.relationships (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households(id) on delete cascade,
  from_member_id uuid not null references public.household_members(id) on delete cascade,
  to_member_id uuid not null references public.household_members(id) on delete cascade,
  relationship_type text not null,
  status text not null default 'active' check (status in ('active','inactive')),
  source text not null default 'pepper',
  confidence numeric(4,3) not null default 1.000 check (confidence >= 0 and confidence <= 1),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (household_id, from_member_id, to_member_id, relationship_type)
);

create table if not exists public.responsibilities (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households(id) on delete cascade,
  responsibility_type text not null,
  subject_member_id uuid references public.household_members(id) on delete cascade,
  owner_member_id uuid references public.household_members(id) on delete set null,
  event_id uuid references public.events(id) on delete cascade,
  task_id uuid references public.tasks(id) on delete cascade,
  status text not null default 'unassigned' check (status in ('unassigned','assigned','confirmed','completed','canceled')),
  starts_at timestamptz,
  ends_at timestamptz,
  source text not null default 'pepper',
  confidence numeric(4,3) not null default 1.000 check (confidence >= 0 and confidence <= 1),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (event_id is not null or task_id is not null or subject_member_id is not null)
);

create unique index if not exists responsibilities_event_type_unique
  on public.responsibilities(household_id, event_id, responsibility_type)
  where event_id is not null;

create table if not exists public.decisions (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households(id) on delete cascade,
  title text not null,
  decision_text text not null,
  owner_member_id uuid references public.household_members(id) on delete set null,
  status text not null default 'decided' check (status in ('proposed','decided','superseded','canceled')),
  effective_at timestamptz,
  source text not null default 'pepper',
  confidence numeric(4,3) not null default 1.000 check (confidence >= 0 and confidence <= 1),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.state_changes (
  id bigint generated by default as identity primary key,
  household_id uuid not null references public.households(id) on delete cascade,
  actor_member_id uuid references public.household_members(id) on delete set null,
  capture_id uuid references public.captures(id) on delete set null,
  entity_type text not null,
  entity_id text,
  change_type text not null,
  before_state jsonb,
  after_state jsonb,
  consequence_summary text,
  confidence numeric(4,3) not null default 1.000 check (confidence >= 0 and confidence <= 1),
  source text not null default 'pepper',
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.locations enable row level security;
alter table public.relationships enable row level security;
alter table public.responsibilities enable row level security;
alter table public.decisions enable row level security;
alter table public.state_changes enable row level security;

create index if not exists locations_household_idx on public.locations(household_id);
create index if not exists relationships_household_idx on public.relationships(household_id);
create index if not exists responsibilities_household_status_idx on public.responsibilities(household_id,status);
create index if not exists responsibilities_owner_idx on public.responsibilities(owner_member_id,status);
create index if not exists decisions_household_status_idx on public.decisions(household_id,status);
create index if not exists state_changes_household_time_idx on public.state_changes(household_id,occurred_at desc);
create index if not exists state_changes_capture_idx on public.state_changes(capture_id);

comment on table public.state_changes is 'Append-first canonical record of meaningful changes to the household state, linked back to the originating Pepper capture when available.';
comment on table public.responsibilities is 'Canonical ownership layer for transportation, preparation, household work, and other family responsibilities.';
