create extension if not exists pgcrypto;
create table public.households (id uuid primary key default gen_random_uuid(), slug text unique not null, name text not null, created_at timestamptz not null default now());
create table public.household_members (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, slug text not null, display_name text not null, role text not null check (role in ('adult_admin','adult','teen','child')), created_at timestamptz not null default now(), unique(household_id,slug));
create table public.events (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, title text not null, person_slug text, starts_at timestamptz not null, ends_at timestamptz, location text, status text not null default 'confirmed' check(status in ('tentative','confirmed','canceled','completed')), visibility text not null default 'household' check(visibility in ('household','private')), owner_member_id uuid references public.household_members(id) on delete set null, kind text not null default 'event', transport_owner_member_id uuid references public.household_members(id) on delete set null, transport_status text check(transport_status in ('unassigned','assigned','confirmed','completed')), source text not null default 'pepper', updated_at timestamptz not null default now(), created_at timestamptz not null default now());
create table public.tasks (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, title text not null, owner_member_id uuid references public.household_members(id) on delete set null, creator_member_id uuid references public.household_members(id) on delete set null, visibility text not null check(visibility in ('household','private')), status text not null default 'open' check(status in ('open','in_progress','completed','canceled')), due_at timestamptz, source text not null default 'pepper', updated_at timestamptz not null default now(), created_at timestamptz not null default now());
create table public.meal_plan (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, meal_date date not null, meal_name text not null, prep_at timestamptz, eat_at timestamptz, owner_member_id uuid references public.household_members(id) on delete set null, updated_at timestamptz not null default now(), unique(household_id,meal_date));
create table public.groceries (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, item text not null, status text not null default 'open' check(status in ('open','completed')), added_by_member_id uuid references public.household_members(id) on delete set null, completed_by_member_id uuid references public.household_members(id) on delete set null, updated_at timestamptz not null default now(), created_at timestamptz not null default now());
create table public.reflections (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, member_id uuid not null references public.household_members(id) on delete cascade, reflection_date date not null default current_date, type text not null check(type in ('gratitude','reflection','good_moment','memory','lesson','concern','win')), original_text text not null, created_at timestamptz not null default now());
create table public.audit_log (id bigserial primary key, household_id uuid not null references public.households(id) on delete cascade, actor_member_id uuid references public.household_members(id) on delete set null, event_type text not null, entity_type text, entity_id text, summary text not null, dedupe_key text, created_at timestamptz not null default now());
