alter table public.tasks
  add column if not exists next_action text not null default '';

create unique index if not exists tasks_household_source_record_unique
  on public.tasks (household_id, lower(btrim(source_record)))
  where btrim(source_record) <> '';

create or replace function private.pepper_task_universal_fields()
returns trigger
language plpgsql
set search_path to 'public', 'private'
as $function$
begin
  new.area := coalesce(nullif(btrim(new.area), ''), 'Personal');
  new.project := coalesce(btrim(new.project), '');
  new.priority := coalesce(nullif(btrim(new.priority), ''), 'P2');
  new.classification := coalesce(nullif(btrim(new.classification), ''), 'Open');
  new.tags := coalesce(new.tags, '{}'::text[]);
  new.notes := coalesce(new.notes, '');
  new.source_record := coalesce(new.source_record, '');
  new.waiting_on := coalesce(new.waiting_on, '');
  new.recurrence := coalesce(nullif(btrim(new.recurrence), ''), 'none');
  new.next_action := coalesce(btrim(new.next_action), '');

  if new.status = 'completed' and (tg_op = 'INSERT' or old.status is distinct from new.status) then
    new.completed_at := coalesce(new.completed_at, now());
  elsif tg_op = 'UPDATE' and old.status = 'completed' and new.status is distinct from 'completed' then
    new.completed_at := null;
  end if;

  return new;
end;
$function$;

update public.tasks
set next_action = left(btrim(coalesce(
  substring(notes from 'Next action:[[:space:]]*([^|]+)'),
  substring(notes from 'Next:[[:space:]]*([^|]+)'),
  ''
)), 1000)
where next_action = ''
  and (notes like '%Next:%' or notes like '%Next action:%');

create table if not exists private.home_brain_task_ledger (
  id bigint generated by default as identity primary key,
  household_id uuid not null references public.households(id) on delete cascade,
  task_id uuid,
  event_type text not null check (event_type in (
    'sync_baseline',
    'task_created',
    'task_updated',
    'task_status_changed',
    'task_completed',
    'task_reopened',
    'task_canceled',
    'task_deleted'
  )),
  changed_at timestamptz not null default now(),
  actor_member_id uuid references public.household_members(id) on delete set null,
  source text not null default 'pepper',
  source_record text not null default '',
  task_area text not null default '',
  task_project text not null default '',
  task_priority text not null default '',
  task_classification text not null default '',
  task_status text not null default '',
  changed_fields text[] not null default '{}'::text[],
  before_state jsonb,
  after_state jsonb,
  sync_status text not null default 'pending' check (sync_status in ('pending', 'exported', 'ignored')),
  export_batch_id uuid,
  exported_at timestamptz,
  notes text not null default '',
  created_at timestamptz not null default now()
);

alter table private.home_brain_task_ledger enable row level security;

comment on table private.home_brain_task_ledger is 'Append-only task bridge for Aegis/Mission Control/home-brain exports. Pepper task changes land here first; external files are regenerated from this ledger and the live task snapshot.';
comment on column private.home_brain_task_ledger.sync_status is 'pending until a home-brain export consumes the event; exported after a snapshot/ledger file has been generated.';

create index if not exists home_brain_task_ledger_household_pending_idx
  on private.home_brain_task_ledger (household_id, sync_status, id);
create index if not exists home_brain_task_ledger_task_idx
  on private.home_brain_task_ledger (task_id, id desc);
create index if not exists home_brain_task_ledger_changed_at_idx
  on private.home_brain_task_ledger (changed_at desc);

create unique index if not exists home_brain_task_ledger_baseline_unique
  on private.home_brain_task_ledger (household_id, task_id)
  where event_type = 'sync_baseline';

create table if not exists private.home_brain_task_exports (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households(id) on delete cascade,
  export_kind text not null check (export_kind in ('snapshot', 'ledger', 'full_refresh')),
  artifact_label text not null,
  task_count integer not null default 0 check (task_count >= 0),
  ledger_count integer not null default 0 check (ledger_count >= 0),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  notes text not null default ''
);

alter table private.home_brain_task_exports enable row level security;

comment on table private.home_brain_task_exports is 'Records Aegis/Mission Control/home-brain task snapshot and ledger exports generated from Pepper.';

create or replace function private.pepper_record_home_brain_task_change()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_before jsonb := case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end;
  v_after jsonb := case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end;
  v_row jsonb := coalesce(v_after, v_before);
  v_changed_fields text[] := '{}'::text[];
  v_event_type text;
  v_actor text;
  v_actor_uuid uuid;
begin
  if tg_op = 'INSERT' then
    v_event_type := 'task_created';
    select coalesce(array_agg(key order by key), '{}'::text[])
      into v_changed_fields
      from jsonb_object_keys(v_after) as keys(key);
  elsif tg_op = 'DELETE' then
    v_event_type := 'task_deleted';
    select coalesce(array_agg(key order by key), '{}'::text[])
      into v_changed_fields
      from jsonb_object_keys(v_before) as keys(key);
  else
    select coalesce(array_agg(coalesce(after_each.key, before_each.key) order by coalesce(after_each.key, before_each.key)), '{}'::text[])
      into v_changed_fields
      from jsonb_each(v_before) as before_each(key, value)
      full join jsonb_each(v_after) as after_each(key, value) using (key)
      where before_each.value is distinct from after_each.value
        and coalesce(after_each.key, before_each.key) <> 'updated_at';

    if coalesce(cardinality(v_changed_fields), 0) = 0 then
      return new;
    end if;

    if old.status is distinct from new.status then
      v_event_type := case
        when new.status = 'completed' then 'task_completed'
        when old.status = 'completed' and new.status <> 'completed' then 'task_reopened'
        when new.status = 'canceled' then 'task_canceled'
        else 'task_status_changed'
      end;
    else
      v_event_type := 'task_updated';
    end if;
  end if;

  v_actor := nullif(current_setting('pepper.actor_member_id', true), '');
  if v_actor is not null and v_actor ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' then
    v_actor_uuid := v_actor::uuid;
  else
    v_actor_uuid := private.pepper_current_member_id();
  end if;

  insert into private.home_brain_task_ledger (
    household_id,
    task_id,
    event_type,
    changed_at,
    actor_member_id,
    source,
    source_record,
    task_area,
    task_project,
    task_priority,
    task_classification,
    task_status,
    changed_fields,
    before_state,
    after_state,
    notes
  ) values (
    nullif(v_row ->> 'household_id', '')::uuid,
    nullif(v_row ->> 'id', '')::uuid,
    v_event_type,
    now(),
    v_actor_uuid,
    coalesce(nullif(v_row ->> 'source', ''), 'pepper'),
    coalesce(v_row ->> 'source_record', ''),
    coalesce(v_row ->> 'area', ''),
    coalesce(v_row ->> 'project', ''),
    coalesce(v_row ->> 'priority', ''),
    coalesce(v_row ->> 'classification', ''),
    coalesce(v_row ->> 'status', ''),
    v_changed_fields,
    v_before,
    v_after,
    case
      when v_event_type = 'task_completed' then coalesce(v_row ->> 'title', 'Task') || ' completed in Pepper.'
      when v_event_type = 'task_reopened' then coalesce(v_row ->> 'title', 'Task') || ' reopened in Pepper.'
      when v_event_type = 'task_deleted' then coalesce(v_row ->> 'title', 'Task') || ' deleted from Pepper.'
      else coalesce(v_row ->> 'title', 'Task') || ' changed in Pepper.'
    end
  );

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$function$;

revoke all on function private.pepper_record_home_brain_task_change() from public, anon, authenticated;

drop trigger if exists trg_pepper_home_brain_task_ledger on public.tasks;
create trigger trg_pepper_home_brain_task_ledger
after insert or update or delete on public.tasks
for each row execute function private.pepper_record_home_brain_task_change();

create or replace view private.home_brain_task_snapshot
with (security_invoker = true)
as
select
  t.household_id,
  h.name as household_name,
  t.id as task_id,
  t.status,
  t.classification,
  t.area,
  t.project,
  t.priority,
  t.due_at,
  (t.due_at at time zone 'America/Los_Angeles')::date as due_date,
  owner.display_name as owner,
  owner.slug as owner_slug,
  creator.display_name as creator,
  t.visibility,
  t.recurrence,
  t.completed_at,
  t.source,
  t.source_record,
  t.title,
  t.next_action,
  t.waiting_on,
  t.tags,
  t.notes,
  t.created_at,
  t.updated_at
from public.tasks t
join public.households h on h.id = t.household_id
left join public.household_members owner on owner.id = t.owner_member_id
left join public.household_members creator on creator.id = t.creator_member_id;

create or replace view private.home_brain_pending_task_changes
with (security_invoker = true)
as
select
  l.id as ledger_id,
  l.household_id,
  h.name as household_name,
  l.task_id,
  l.event_type,
  l.changed_at,
  actor.display_name as actor,
  l.source,
  l.source_record,
  l.task_area as area,
  l.task_project as project,
  l.task_priority as priority,
  l.task_classification as classification,
  l.task_status as status,
  l.changed_fields,
  l.sync_status,
  l.export_batch_id,
  l.exported_at,
  l.notes,
  l.before_state,
  l.after_state
from private.home_brain_task_ledger l
join public.households h on h.id = l.household_id
left join public.household_members actor on actor.id = l.actor_member_id
where l.sync_status = 'pending';

insert into private.home_brain_task_ledger (
  household_id,
  task_id,
  event_type,
  changed_at,
  actor_member_id,
  source,
  source_record,
  task_area,
  task_project,
  task_priority,
  task_classification,
  task_status,
  changed_fields,
  before_state,
  after_state,
  sync_status,
  notes
)
select
  t.household_id,
  t.id,
  'sync_baseline',
  now(),
  null,
  coalesce(t.source, 'pepper'),
  coalesce(t.source_record, ''),
  coalesce(t.area, ''),
  coalesce(t.project, ''),
  coalesce(t.priority, ''),
  coalesce(t.classification, ''),
  coalesce(t.status, ''),
  array['baseline'],
  null,
  to_jsonb(t),
  'pending',
  'Baseline event for Aegis/Mission Control/home-brain sync.'
from public.tasks t
where not exists (
  select 1
  from private.home_brain_task_ledger l
  where l.household_id = t.household_id
    and l.task_id = t.id
    and l.event_type = 'sync_baseline'
);
