-- V6 Phase 1: One Brain capture reconciliation foundation.
--
-- Captures remain append-first input history. Canonical writes are applied only
-- through private.apply_capture_plan(), in one database transaction, with an
-- idempotency ledger and capture/actor trace context for downstream triggers.

alter table public.captures
  add column if not exists sharing_scope text not null default 'member_private',
  add column if not exists remaining_ambiguities jsonb not null default '[]'::jsonb,
  add column if not exists reconciled_by_member_id uuid references public.household_members(id) on delete set null,
  add column if not exists reconciled_at timestamptz,
  add column if not exists reconciliation_version integer;

alter table public.captures
  drop constraint if exists captures_sharing_scope_check,
  add constraint captures_sharing_scope_check
    check (sharing_scope in ('member_private', 'household')),
  drop constraint if exists captures_remaining_ambiguities_array_check,
  add constraint captures_remaining_ambiguities_array_check
    check (jsonb_typeof(remaining_ambiguities) = 'array'),
  drop constraint if exists captures_aegis_record_ids_array_check,
  add constraint captures_aegis_record_ids_array_check
    check (aegis_record_ids is null or jsonb_typeof(aegis_record_ids) = 'array');

-- "pending" was ambiguous: it could mean untouched, failed, or waiting for a
-- person. Preserve that history without claiming that any canonical write was
-- applied. Existing review rows remain reviewable; all other pending rows return
-- to the explicit captured state.
alter table public.captures drop constraint if exists captures_aegis_sync_status_check;

update public.captures
set aegis_sync_status = case
      when status in ('partially_applied', 'needs_review') then 'needs_review'
      when status = 'dismissed' then 'not_applicable'
      else 'captured'
    end,
    aegis_record_ids = coalesce(aegis_record_ids, '[]'::jsonb)
where aegis_sync_status = 'pending'
   or aegis_sync_status is null
   or aegis_record_ids is null;

alter table public.captures
  alter column aegis_sync_status set default 'captured',
  alter column aegis_record_ids set default '[]'::jsonb,
  add constraint captures_aegis_sync_status_check
    check (aegis_sync_status in ('captured', 'synced', 'needs_review', 'failed', 'not_applicable'));

drop index if exists public.captures_aegis_pending_idx;
create index if not exists captures_reconciliation_queue_idx
  on public.captures (member_id, captured_at desc)
  where aegis_sync_status in ('captured', 'needs_review', 'failed');

comment on column public.captures.sharing_scope is
  'Privacy of the raw capture. member_private is the default; household requires explicit capture semantics.';
comment on column public.captures.remaining_ambiguities is
  'Explicit unresolved portions of a capture. Pepper must not invent writes to empty this list.';
comment on column public.captures.aegis_sync_status is
  'Canonical reconciliation state. captured is new/unapplied; synced is fully applied; needs_review is explicit; failed is retryable; not_applicable is reviewed with no canonical write.';

create or replace function private.pepper_preserve_capture_input()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if new.household_id is distinct from old.household_id
     or new.member_id is distinct from old.member_id
     or new.source is distinct from old.source
     or new.original_text is distinct from old.original_text
     or new.captured_at is distinct from old.captured_at
     or new.dedupe_key is distinct from old.dedupe_key then
    raise exception 'Original capture input is immutable.' using errcode = '55000';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_pepper_preserve_capture_input on public.captures;
create trigger trg_pepper_preserve_capture_input
before update on public.captures
for each row execute function private.pepper_preserve_capture_input();

revoke execute on function private.pepper_preserve_capture_input() from public, anon, authenticated, service_role;

create table if not exists private.capture_plan_applications (
  id bigint generated by default as identity primary key,
  capture_id uuid not null references public.captures(id) on delete cascade,
  household_id uuid not null references public.households(id) on delete cascade,
  actor_member_id uuid not null references public.household_members(id) on delete restrict,
  idempotency_key text not null check (length(btrim(idempotency_key)) between 1 and 200),
  plan_hash text not null,
  plan_kind text not null check (plan_kind in ('initial', 'review_resolution', 'backlog')),
  outcome text not null check (outcome in ('applied', 'partially_applied', 'needs_review')),
  result jsonb not null,
  created_at timestamptz not null default now(),
  unique (capture_id, idempotency_key)
);

alter table private.capture_plan_applications enable row level security;
revoke all on private.capture_plan_applications from public, anon, authenticated, service_role;
create index if not exists capture_plan_applications_capture_idx
  on private.capture_plan_applications (capture_id, created_at desc);

comment on table private.capture_plan_applications is
  'Private idempotency ledger for atomic capture plans. It stores no raw capture text.';

alter table public.responsibilities
  add column if not exists originating_capture_id uuid references public.captures(id) on delete set null,
  add column if not exists last_actor_member_id uuid references public.household_members(id) on delete set null;

alter table public.decisions
  add column if not exists originating_capture_id uuid references public.captures(id) on delete set null,
  add column if not exists last_actor_member_id uuid references public.household_members(id) on delete set null;

alter table public.consequences
  add column if not exists originating_capture_id uuid references public.captures(id) on delete set null,
  add column if not exists last_actor_member_id uuid references public.household_members(id) on delete set null;

alter table public.audit_log
  add column if not exists capture_id uuid references public.captures(id) on delete set null;

create index if not exists responsibilities_originating_capture_idx
  on public.responsibilities (originating_capture_id)
  where originating_capture_id is not null;
create index if not exists decisions_originating_capture_idx
  on public.decisions (originating_capture_id)
  where originating_capture_id is not null;
create index if not exists consequences_originating_capture_idx
  on public.consequences (originating_capture_id)
  where originating_capture_id is not null;
create index if not exists audit_log_capture_idx
  on public.audit_log (capture_id)
  where capture_id is not null;

create or replace function private.pepper_assert_jsonb_keys(
  value_input jsonb,
  allowed_keys_input text[],
  context_input text
)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
  unexpected_key text;
begin
  if value_input is null or pg_catalog.jsonb_typeof(value_input) <> 'object' then
    raise exception '% must be a JSON object.', context_input using errcode = '22023';
  end if;

  select key into unexpected_key
  from pg_catalog.jsonb_object_keys(value_input) as keys(key)
  where not (key = any(allowed_keys_input))
  order by key
  limit 1;

  if unexpected_key is not null then
    raise exception 'Unexpected key "%" in %.', unexpected_key, context_input using errcode = '22023';
  end if;
end;
$$;

create or replace function private.pepper_assert_household_member(
  household_id_input uuid,
  member_id_input uuid,
  context_input text
)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if member_id_input is not null and not exists (
    select 1
    from public.household_members hm
    where hm.id = member_id_input
      and hm.household_id = household_id_input
  ) then
    raise exception '% is not a member of this household.', context_input using errcode = '23503';
  end if;
end;
$$;

create or replace function private.pepper_stamp_state_change_context()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  context_capture_id uuid;
  context_actor_id uuid;
begin
  context_capture_id := nullif(pg_catalog.current_setting('pepper.capture_id', true), '')::uuid;
  context_actor_id := nullif(pg_catalog.current_setting('pepper.actor_member_id', true), '')::uuid;

  new.capture_id := coalesce(new.capture_id, context_capture_id);
  new.actor_member_id := coalesce(new.actor_member_id, context_actor_id);

  if new.capture_id is not null and not exists (
    select 1 from public.captures c
    where c.id = new.capture_id and c.household_id = new.household_id
  ) then
    raise exception 'State change capture does not belong to the household.' using errcode = '23503';
  end if;
  perform private.pepper_assert_household_member(new.household_id, new.actor_member_id, 'State change actor');
  return new;
end;
$$;

drop trigger if exists trg_pepper_stamp_state_change_context on public.state_changes;
create trigger trg_pepper_stamp_state_change_context
before insert on public.state_changes
for each row execute function private.pepper_stamp_state_change_context();
revoke execute on function private.pepper_stamp_state_change_context() from public, anon, authenticated, service_role;

create or replace function private.pepper_stamp_canonical_context()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  context_capture_id uuid;
  context_actor_id uuid;
begin
  context_capture_id := nullif(pg_catalog.current_setting('pepper.capture_id', true), '')::uuid;
  context_actor_id := nullif(pg_catalog.current_setting('pepper.actor_member_id', true), '')::uuid;

  if context_capture_id is not null then
    if not exists (
      select 1 from public.captures c
      where c.id = context_capture_id and c.household_id = new.household_id
    ) then
      raise exception 'Canonical write capture does not belong to the household.' using errcode = '23503';
    end if;
    new.originating_capture_id := coalesce(new.originating_capture_id, context_capture_id);
    new.last_actor_member_id := context_actor_id;
  end if;

  perform private.pepper_assert_household_member(new.household_id, new.last_actor_member_id, 'Canonical write actor');
  return new;
end;
$$;

drop trigger if exists trg_pepper_stamp_responsibility_context on public.responsibilities;
create trigger trg_pepper_stamp_responsibility_context
before insert or update on public.responsibilities
for each row execute function private.pepper_stamp_canonical_context();

drop trigger if exists trg_pepper_stamp_decision_context on public.decisions;
create trigger trg_pepper_stamp_decision_context
before insert or update on public.decisions
for each row execute function private.pepper_stamp_canonical_context();

drop trigger if exists trg_pepper_stamp_consequence_context on public.consequences;
create trigger trg_pepper_stamp_consequence_context
before insert or update on public.consequences
for each row execute function private.pepper_stamp_canonical_context();
revoke execute on function private.pepper_stamp_canonical_context() from public, anon, authenticated, service_role;

create or replace function private.pepper_stamp_audit_context()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  new.capture_id := coalesce(
    new.capture_id,
    nullif(pg_catalog.current_setting('pepper.capture_id', true), '')::uuid
  );
  new.actor_member_id := coalesce(
    new.actor_member_id,
    nullif(pg_catalog.current_setting('pepper.actor_member_id', true), '')::uuid
  );
  if new.capture_id is not null and not exists (
    select 1 from public.captures c
    where c.id = new.capture_id and c.household_id = new.household_id
  ) then
    raise exception 'Audit capture does not belong to the household.' using errcode = '23503';
  end if;
  perform private.pepper_assert_household_member(new.household_id, new.actor_member_id, 'Audit actor');
  return new;
end;
$$;

drop trigger if exists trg_pepper_stamp_audit_context on public.audit_log;
create trigger trg_pepper_stamp_audit_context
before insert on public.audit_log
for each row execute function private.pepper_stamp_audit_context();
revoke execute on function private.pepper_stamp_audit_context() from public, anon, authenticated, service_role;

create or replace function private.apply_capture_plan(
  capture_id_input uuid,
  actor_member_id_input uuid,
  idempotency_key_input text,
  plan_input jsonb
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  capture_row public.captures%rowtype;
  prior_application private.capture_plan_applications%rowtype;
  plan_hash_value text;
  plan_kind_value text;
  outcome_value text;
  sync_status_value text;
  safe_subset_value boolean;
  writes_value jsonb;
  facts_value jsonb;
  ambiguities_value jsonb;
  existing_refs_value jsonb;
  existing_ref_value jsonb;
  write_value jsonb;
  operation_value text;
  record_id_value uuid;
  owner_id_value uuid;
  subject_id_value uuid;
  event_id_value uuid;
  task_id_value uuid;
  starts_at_value timestamptz;
  ends_at_value timestamptz;
  before_value jsonb;
  after_value jsonb;
  change_value jsonb;
  changes_value jsonb := '[]'::jsonb;
  refs_value jsonb := '[]'::jsonb;
  destinations_value text[] := array[]::text[];
  combined_refs_value jsonb;
  destination_value text;
  result_value jsonb;
  write_count integer;
  title_value text;
  status_value text;
  visibility_value text;
  source_value text;
  meal_date_value date;
  audit_event_type_value text;
  audit_summary_value text;
begin
  if capture_id_input is null or actor_member_id_input is null then
    raise exception 'Capture and actor are required.' using errcode = '22023';
  end if;
  if length(btrim(coalesce(idempotency_key_input, ''))) not between 1 and 200 then
    raise exception 'A valid idempotency key is required.' using errcode = '22023';
  end if;

  perform private.pepper_assert_jsonb_keys(
    plan_input,
    array['version','kind','outcome','safe_subset_declared','extracted_facts','remaining_ambiguities','writes','resolution','existing_records'],
    'capture plan'
  );
  if coalesce((plan_input->>'version')::integer, 0) <> 1 then
    raise exception 'Unsupported capture plan version.' using errcode = '22023';
  end if;

  plan_kind_value := plan_input->>'kind';
  outcome_value := plan_input->>'outcome';
  safe_subset_value := coalesce((plan_input->>'safe_subset_declared')::boolean, false);
  writes_value := coalesce(plan_input->'writes', '[]'::jsonb);
  facts_value := coalesce(plan_input->'extracted_facts', '[]'::jsonb);
  ambiguities_value := coalesce(plan_input->'remaining_ambiguities', '[]'::jsonb);
  existing_refs_value := coalesce(plan_input->'existing_records', '[]'::jsonb);

  if plan_kind_value not in ('initial', 'review_resolution', 'backlog') then
    raise exception 'Invalid capture plan kind.' using errcode = '22023';
  end if;
  if outcome_value not in ('applied', 'partially_applied', 'needs_review') then
    raise exception 'Invalid capture plan outcome.' using errcode = '22023';
  end if;
  if pg_catalog.jsonb_typeof(writes_value) <> 'array'
     or pg_catalog.jsonb_typeof(facts_value) <> 'array'
     or pg_catalog.jsonb_typeof(ambiguities_value) <> 'array'
     or pg_catalog.jsonb_typeof(existing_refs_value) <> 'array' then
    raise exception 'Plan writes, facts, ambiguities, and existing records must be arrays.' using errcode = '22023';
  end if;
  if length(plan_input::text) > 100000 then
    raise exception 'Capture plan is too large.' using errcode = '22023';
  end if;

  write_count := pg_catalog.jsonb_array_length(writes_value);
  if outcome_value = 'applied'
     and write_count = 0
     and not (plan_kind_value = 'review_resolution' and plan_input->>'resolution' = 'no_change_required')
     and not (
       plan_kind_value = 'backlog'
       and plan_input->>'resolution' = 'existing_records_verified'
       and pg_catalog.jsonb_array_length(existing_refs_value) > 0
     ) then
    raise exception 'Applied plans require a canonical write or an explicit verified resolution.' using errcode = '22023';
  end if;
  if outcome_value = 'applied' and pg_catalog.jsonb_array_length(ambiguities_value) <> 0 then
    raise exception 'Applied plans cannot retain ambiguity.' using errcode = '22023';
  end if;
  if outcome_value = 'partially_applied'
     and (write_count = 0 or not safe_subset_value or pg_catalog.jsonb_array_length(ambiguities_value) = 0) then
    raise exception 'Partial plans require an explicit safe subset, writes, and remaining ambiguity.' using errcode = '22023';
  end if;
  if outcome_value = 'needs_review'
     and (write_count <> 0 or pg_catalog.jsonb_array_length(ambiguities_value) = 0) then
    raise exception 'Needs-review plans cannot write and must describe remaining ambiguity.' using errcode = '22023';
  end if;
  if plan_kind_value <> 'backlog' and pg_catalog.jsonb_array_length(existing_refs_value) <> 0 then
    raise exception 'Only backlog reconciliation can declare existing canonical records.' using errcode = '22023';
  end if;
  if pg_catalog.jsonb_array_length(existing_refs_value) > 0
     and not (
       plan_kind_value = 'backlog'
       and plan_input->>'resolution' = 'existing_records_verified'
       and outcome_value = 'applied'
       and write_count = 0
       and pg_catalog.jsonb_array_length(ambiguities_value) = 0
     ) then
    raise exception 'Existing records require a write-free, fully verified backlog resolution.' using errcode = '22023';
  end if;

  plan_hash_value := pg_catalog.encode(
    pg_catalog.sha256(pg_catalog.convert_to(plan_input::text, 'UTF8')),
    'hex'
  );

  select * into capture_row
  from public.captures c
  where c.id = capture_id_input
  for update;

  if not found or capture_row.member_id is distinct from actor_member_id_input then
    raise exception 'Capture not found or not permitted.' using errcode = '42501';
  end if;
  perform private.pepper_assert_household_member(capture_row.household_id, actor_member_id_input, 'Capture actor');

  select * into prior_application
  from private.capture_plan_applications a
  where a.capture_id = capture_id_input
    and a.idempotency_key = btrim(idempotency_key_input);

  if found then
    if prior_application.plan_hash <> plan_hash_value
       or prior_application.actor_member_id <> actor_member_id_input then
      raise exception 'Idempotency key was already used for a different capture plan.' using errcode = '23505';
    end if;
    return prior_application.result || pg_catalog.jsonb_build_object('idempotent_replay', true);
  end if;

  if plan_kind_value = 'initial' and capture_row.status <> 'captured' then
    raise exception 'Initial reconciliation is only valid for a captured item.' using errcode = '55000';
  end if;
  if plan_kind_value = 'review_resolution'
     and capture_row.status not in ('partially_applied', 'needs_review') then
    raise exception 'Only a review item can be resolved.' using errcode = '55000';
  end if;
  if plan_kind_value = 'backlog'
     and not (
       capture_row.status in ('captured', 'partially_applied', 'needs_review')
       or (capture_row.status = 'applied' and capture_row.aegis_sync_status in ('captured','failed'))
     ) then
    raise exception 'Capture is not eligible for backlog reconciliation.' using errcode = '55000';
  end if;

  perform pg_catalog.set_config('pepper.capture_id', capture_id_input::text, true);
  perform pg_catalog.set_config('pepper.actor_member_id', actor_member_id_input::text, true);

  for existing_ref_value in select value from pg_catalog.jsonb_array_elements(existing_refs_value)
  loop
    perform private.pepper_assert_jsonb_keys(existing_ref_value, array['entity_type','record_id'], 'existing canonical record');
    operation_value := existing_ref_value->>'entity_type';
    record_id_value := nullif(existing_ref_value->>'record_id','')::uuid;
    if operation_value not in ('task','event','grocery','meal','responsibility','decision')
       or record_id_value is null
       or not private.pepper_record_ref_exists(capture_row.household_id, operation_value, record_id_value) then
      raise exception 'Existing canonical record is missing or outside the capture household.' using errcode = 'P0003';
    end if;
    refs_value := refs_value || pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_object(
      'entity_type', operation_value, 'record_id', record_id_value
    ));
    destinations_value := pg_catalog.array_append(destinations_value, operation_value);
  end loop;

  for write_value in select value from pg_catalog.jsonb_array_elements(writes_value)
  loop
    perform private.pepper_assert_jsonb_keys(
      write_value,
      array[
        'operation','record_id','title','item','owner_member_id','subject_member_id',
        'event_id','task_id','person_slug','starts_at','ends_at','due_at','location',
        'status','visibility','kind','transport_owner_member_id','transport_status',
        'source','responsibility_type','meal_date','meal_name','prep_at','eat_at',
        'decision_text','effective_at','confidence','metadata','audit_event_type','audit_summary'
      ],
      'capture plan write'
    );

    operation_value := write_value->>'operation';
    record_id_value := nullif(write_value->>'record_id', '')::uuid;
    if record_id_value is null then
      raise exception 'Every canonical write requires a declared record_id.' using errcode = '22023';
    end if;

    owner_id_value := nullif(write_value->>'owner_member_id', '')::uuid;
    subject_id_value := nullif(write_value->>'subject_member_id', '')::uuid;
    event_id_value := nullif(write_value->>'event_id', '')::uuid;
    task_id_value := nullif(write_value->>'task_id', '')::uuid;
    perform private.pepper_assert_household_member(capture_row.household_id, owner_id_value, 'Owner');
    perform private.pepper_assert_household_member(capture_row.household_id, subject_id_value, 'Subject');

    audit_event_type_value := nullif(btrim(write_value->>'audit_event_type'), '');
    audit_summary_value := nullif(btrim(write_value->>'audit_summary'), '');
    if (audit_event_type_value is null) <> (audit_summary_value is null)
       or length(coalesce(audit_event_type_value, '')) > 100
       or length(coalesce(audit_summary_value, '')) > 500 then
      raise exception 'Audit type and summary must be supplied together and remain within limits.' using errcode = '22023';
    end if;

    if operation_value = 'task.create' then
      perform private.pepper_assert_jsonb_keys(
        write_value,
        array['operation','record_id','title','owner_member_id','due_at','status','visibility','source','metadata','audit_event_type','audit_summary'],
        operation_value
      );
      title_value := btrim(coalesce(write_value->>'title', ''));
      if title_value = '' then raise exception 'Task title is required.' using errcode = '22023'; end if;
      visibility_value := coalesce(nullif(write_value->>'visibility', ''), 'household');
      if visibility_value not in ('household','private') then raise exception 'Invalid task visibility.' using errcode = '22023'; end if;
      if visibility_value = 'private' and owner_id_value is distinct from actor_member_id_input then
        raise exception 'A private task must belong to the capture author.' using errcode = '42501';
      end if;
      status_value := coalesce(nullif(write_value->>'status', ''), 'open');
      source_value := coalesce(nullif(write_value->>'source', ''), 'pepper_capture');
      starts_at_value := nullif(write_value->>'due_at', '')::timestamptz;
      insert into public.tasks(
        id, household_id, title, owner_member_id, creator_member_id,
        visibility, status, due_at, source
      ) values (
        record_id_value, capture_row.household_id, title_value, owner_id_value,
        actor_member_id_input, visibility_value, status_value, starts_at_value, source_value
      );
      select to_jsonb(t) into after_value from public.tasks t where t.id = record_id_value;

    elsif operation_value = 'task.update' then
      perform private.pepper_assert_jsonb_keys(
        write_value,
        array['operation','record_id','title','owner_member_id','due_at','status','visibility','source','metadata','audit_event_type','audit_summary'],
        operation_value
      );
      select to_jsonb(t) into before_value
      from public.tasks t
      where t.id = record_id_value and t.household_id = capture_row.household_id
      for update;
      if before_value is null then raise exception 'Required task does not exist.' using errcode = 'P0002'; end if;
      if before_value->>'visibility' = 'private' and before_value->>'owner_member_id' is distinct from actor_member_id_input::text then
        raise exception 'That task is private.' using errcode = '42501';
      end if;
      if write_value ? 'title' and btrim(coalesce(write_value->>'title','')) = '' then
        raise exception 'Task title cannot be empty.' using errcode = '22023';
      end if;
      if coalesce(write_value->>'visibility', before_value->>'visibility') = 'private'
         and (case when write_value ? 'owner_member_id' then write_value->>'owner_member_id' else before_value->>'owner_member_id' end)
             is distinct from actor_member_id_input::text then
        raise exception 'A private task must belong to the capture author.' using errcode = '42501';
      end if;
      update public.tasks t set
        title = case when write_value ? 'title' then btrim(write_value->>'title') else t.title end,
        owner_member_id = case when write_value ? 'owner_member_id' then owner_id_value else t.owner_member_id end,
        due_at = case when write_value ? 'due_at' then nullif(write_value->>'due_at','')::timestamptz else t.due_at end,
        status = case when write_value ? 'status' then write_value->>'status' else t.status end,
        visibility = case when write_value ? 'visibility' then write_value->>'visibility' else t.visibility end,
        source = case when write_value ? 'source' then write_value->>'source' else t.source end,
        updated_at = now()
      where t.id = record_id_value and t.household_id = capture_row.household_id;
      if not found then raise exception 'Required task update failed.' using errcode = 'P0002'; end if;
      select to_jsonb(t) into after_value from public.tasks t where t.id = record_id_value;

    elsif operation_value = 'event.create' then
      perform private.pepper_assert_jsonb_keys(
        write_value,
        array['operation','record_id','title','person_slug','starts_at','ends_at','location','status','visibility','owner_member_id','kind','transport_owner_member_id','transport_status','source','metadata','audit_event_type','audit_summary'],
        operation_value
      );
      title_value := btrim(coalesce(write_value->>'title', ''));
      starts_at_value := nullif(write_value->>'starts_at', '')::timestamptz;
      if title_value = '' or starts_at_value is null then raise exception 'Event title and start are required.' using errcode = '22023'; end if;
      visibility_value := coalesce(nullif(write_value->>'visibility', ''), 'household');
      if visibility_value not in ('household','private') then raise exception 'Invalid event visibility.' using errcode = '22023'; end if;
      if visibility_value = 'private' and owner_id_value is distinct from actor_member_id_input then
        raise exception 'A private event must belong to the capture author.' using errcode = '42501';
      end if;
      if write_value->>'person_slug' is not null and not exists (
        select 1 from public.household_members hm
        where hm.household_id = capture_row.household_id and hm.slug = write_value->>'person_slug'
      ) then
        raise exception 'Event person is not in this household.' using errcode = '23503';
      end if;
      subject_id_value := nullif(write_value->>'transport_owner_member_id', '')::uuid;
      perform private.pepper_assert_household_member(capture_row.household_id, subject_id_value, 'Transportation owner');
      ends_at_value := nullif(write_value->>'ends_at', '')::timestamptz;
      insert into public.events(
        id, household_id, title, person_slug, starts_at, ends_at, location,
        status, visibility, owner_member_id, kind, transport_owner_member_id,
        transport_status, source
      ) values (
        record_id_value, capture_row.household_id, title_value, write_value->>'person_slug',
        starts_at_value, ends_at_value, nullif(write_value->>'location',''),
        coalesce(nullif(write_value->>'status',''),'confirmed'), visibility_value,
        owner_id_value, coalesce(nullif(write_value->>'kind',''),'event'), subject_id_value,
        nullif(write_value->>'transport_status',''), coalesce(nullif(write_value->>'source',''),'pepper')
      );
      select to_jsonb(e) into after_value from public.events e where e.id = record_id_value;

    elsif operation_value = 'event.update' then
      perform private.pepper_assert_jsonb_keys(
        write_value,
        array['operation','record_id','title','person_slug','starts_at','ends_at','location','status','visibility','owner_member_id','kind','transport_owner_member_id','transport_status','source','metadata','audit_event_type','audit_summary'],
        operation_value
      );
      select to_jsonb(e) into before_value
      from public.events e
      where e.id = record_id_value and e.household_id = capture_row.household_id
      for update;
      if before_value is null then raise exception 'Required event does not exist.' using errcode = 'P0002'; end if;
      if before_value->>'visibility' = 'private' and before_value->>'owner_member_id' is distinct from actor_member_id_input::text then
        raise exception 'That event is private.' using errcode = '42501';
      end if;
      if write_value ? 'title' and btrim(coalesce(write_value->>'title','')) = '' then
        raise exception 'Event title cannot be empty.' using errcode = '22023';
      end if;
      if coalesce(write_value->>'visibility', before_value->>'visibility') = 'private'
         and (case when write_value ? 'owner_member_id' then write_value->>'owner_member_id' else before_value->>'owner_member_id' end)
             is distinct from actor_member_id_input::text then
        raise exception 'A private event must belong to the capture author.' using errcode = '42501';
      end if;
      if write_value ? 'person_slug'
         and nullif(write_value->>'person_slug','') is not null
         and not exists (
           select 1 from public.household_members hm
           where hm.household_id=capture_row.household_id and hm.slug=write_value->>'person_slug'
         ) then
        raise exception 'Event person is not in this household.' using errcode = '23503';
      end if;
      subject_id_value := nullif(write_value->>'transport_owner_member_id', '')::uuid;
      perform private.pepper_assert_household_member(capture_row.household_id, subject_id_value, 'Transportation owner');
      update public.events e set
        title = case when write_value ? 'title' then btrim(write_value->>'title') else e.title end,
        person_slug = case when write_value ? 'person_slug' then nullif(write_value->>'person_slug','') else e.person_slug end,
        starts_at = case when write_value ? 'starts_at' then nullif(write_value->>'starts_at','')::timestamptz else e.starts_at end,
        ends_at = case when write_value ? 'ends_at' then nullif(write_value->>'ends_at','')::timestamptz else e.ends_at end,
        location = case when write_value ? 'location' then nullif(write_value->>'location','') else e.location end,
        status = case when write_value ? 'status' then write_value->>'status' else e.status end,
        visibility = case when write_value ? 'visibility' then write_value->>'visibility' else e.visibility end,
        owner_member_id = case when write_value ? 'owner_member_id' then owner_id_value else e.owner_member_id end,
        kind = case when write_value ? 'kind' then write_value->>'kind' else e.kind end,
        transport_owner_member_id = case when write_value ? 'transport_owner_member_id' then subject_id_value else e.transport_owner_member_id end,
        transport_status = case when write_value ? 'transport_status' then nullif(write_value->>'transport_status','') else e.transport_status end,
        source = case when write_value ? 'source' then write_value->>'source' else e.source end,
        updated_at = now()
      where e.id = record_id_value and e.household_id = capture_row.household_id;
      if not found then raise exception 'Required event update failed.' using errcode = 'P0002'; end if;
      select to_jsonb(e) into after_value from public.events e where e.id = record_id_value;

    elsif operation_value = 'grocery.create' then
      perform private.pepper_assert_jsonb_keys(
        write_value,
        array['operation','record_id','item','status','metadata','audit_event_type','audit_summary'],
        operation_value
      );
      title_value := btrim(coalesce(write_value->>'item', ''));
      if title_value = '' then raise exception 'Grocery item is required.' using errcode = '22023'; end if;
      insert into public.groceries(id, household_id, item, status, added_by_member_id)
      values (record_id_value, capture_row.household_id, title_value, coalesce(nullif(write_value->>'status',''),'open'), actor_member_id_input);
      select to_jsonb(g) into after_value from public.groceries g where g.id = record_id_value;
      insert into public.state_changes(
        household_id, entity_type, entity_id, change_type, before_state, after_state,
        consequence_summary, confidence, source
      ) values (
        capture_row.household_id, 'grocery', record_id_value::text, 'grocery_created', null,
        after_value, 'A grocery item was added.', 1.000, 'pepper_capture'
      );

    elsif operation_value = 'meal.upsert' then
      perform private.pepper_assert_jsonb_keys(
        write_value,
        array['operation','record_id','meal_date','meal_name','prep_at','eat_at','owner_member_id','metadata','audit_event_type','audit_summary'],
        operation_value
      );
      meal_date_value := nullif(write_value->>'meal_date','')::date;
      title_value := btrim(coalesce(write_value->>'meal_name',''));
      if meal_date_value is null or title_value = '' then raise exception 'Meal date and name are required.' using errcode = '22023'; end if;
      select to_jsonb(mp) into before_value
      from public.meal_plan mp
      where mp.household_id = capture_row.household_id and mp.meal_date = meal_date_value
      for update;
      if before_value is not null and before_value->>'id' <> record_id_value::text then
        raise exception 'Declared meal record does not match the canonical meal.' using errcode = 'P0002';
      end if;
      if before_value is null then
        insert into public.meal_plan(id, household_id, meal_date, meal_name, prep_at, eat_at, owner_member_id, updated_at)
        values (
          record_id_value, capture_row.household_id, meal_date_value, title_value,
          nullif(write_value->>'prep_at','')::timestamptz,
          nullif(write_value->>'eat_at','')::timestamptz,
          owner_id_value, now()
        );
      else
        update public.meal_plan mp set
          meal_name = title_value,
          prep_at = case when write_value ? 'prep_at' then nullif(write_value->>'prep_at','')::timestamptz else mp.prep_at end,
          eat_at = case when write_value ? 'eat_at' then nullif(write_value->>'eat_at','')::timestamptz else mp.eat_at end,
          owner_member_id = case when write_value ? 'owner_member_id' then owner_id_value else mp.owner_member_id end,
          updated_at = now()
        where mp.id = record_id_value and mp.household_id = capture_row.household_id;
        if not found then raise exception 'Required meal update failed.' using errcode = 'P0002'; end if;
      end if;
      select to_jsonb(mp) into after_value from public.meal_plan mp where mp.id = record_id_value;
      insert into public.state_changes(
        household_id, entity_type, entity_id, change_type, before_state, after_state,
        consequence_summary, confidence, source
      ) values (
        capture_row.household_id, 'meal', record_id_value::text,
        case when before_value is null then 'meal_created' else 'meal_updated' end,
        before_value, after_value, 'The family meal plan changed.', 1.000, 'pepper_capture'
      );

    elsif operation_value = 'responsibility.upsert' then
      perform private.pepper_assert_jsonb_keys(
        write_value,
        array['operation','record_id','responsibility_type','subject_member_id','owner_member_id','event_id','task_id','status','starts_at','ends_at','source','confidence','metadata','audit_event_type','audit_summary'],
        operation_value
      );
      title_value := btrim(coalesce(write_value->>'responsibility_type',''));
      if title_value = '' or (event_id_value is null and task_id_value is null and subject_id_value is null) then
        raise exception 'Responsibility type and subject are required.' using errcode = '22023';
      end if;
      if event_id_value is not null and not exists (
        select 1 from public.events e where e.id = event_id_value and e.household_id = capture_row.household_id
      ) then raise exception 'Responsibility event does not exist.' using errcode = '23503'; end if;
      if task_id_value is not null and not exists (
        select 1 from public.tasks t where t.id = task_id_value and t.household_id = capture_row.household_id
      ) then raise exception 'Responsibility task does not exist.' using errcode = '23503'; end if;
      select to_jsonb(r) into before_value
      from public.responsibilities r
      where r.household_id = capture_row.household_id
        and r.responsibility_type = title_value
        and r.event_id is not distinct from event_id_value
        and r.task_id is not distinct from task_id_value
      limit 1 for update;
      if before_value is not null and before_value->>'id' <> record_id_value::text then
        raise exception 'Declared responsibility does not match canonical state.' using errcode = 'P0002';
      end if;
      if before_value is null then
        insert into public.responsibilities(
          id, household_id, responsibility_type, subject_member_id, owner_member_id,
          event_id, task_id, status, starts_at, ends_at, source, confidence
        ) values (
          record_id_value, capture_row.household_id, title_value, subject_id_value, owner_id_value,
          event_id_value, task_id_value, coalesce(nullif(write_value->>'status',''),'unassigned'),
          nullif(write_value->>'starts_at','')::timestamptz,
          nullif(write_value->>'ends_at','')::timestamptz,
          coalesce(nullif(write_value->>'source',''),'pepper_capture'),
          coalesce(nullif(write_value->>'confidence','')::numeric, 1.000)
        );
      else
        update public.responsibilities r set
          subject_member_id = case when write_value ? 'subject_member_id' then subject_id_value else r.subject_member_id end,
          owner_member_id = case when write_value ? 'owner_member_id' then owner_id_value else r.owner_member_id end,
          status = coalesce(nullif(write_value->>'status',''), r.status),
          starts_at = case when write_value ? 'starts_at' then nullif(write_value->>'starts_at','')::timestamptz else r.starts_at end,
          ends_at = case when write_value ? 'ends_at' then nullif(write_value->>'ends_at','')::timestamptz else r.ends_at end,
          source = coalesce(nullif(write_value->>'source',''), r.source),
          confidence = coalesce(nullif(write_value->>'confidence','')::numeric, r.confidence),
          updated_at = now()
        where r.id = record_id_value;
      end if;
      select to_jsonb(r) into after_value from public.responsibilities r where r.id = record_id_value;
      insert into public.state_changes(
        household_id, entity_type, entity_id, change_type, before_state, after_state,
        consequence_summary, confidence, source
      ) values (
        capture_row.household_id, 'responsibility', record_id_value::text,
        case when before_value is null then 'responsibility_created' else 'responsibility_updated' end,
        before_value, after_value, 'A family responsibility changed.', 1.000, 'pepper_capture'
      );

    elsif operation_value = 'decision.create' then
      perform private.pepper_assert_jsonb_keys(
        write_value,
        array['operation','record_id','title','decision_text','owner_member_id','status','effective_at','source','confidence','metadata','audit_event_type','audit_summary'],
        operation_value
      );
      title_value := btrim(coalesce(write_value->>'title',''));
      if title_value = '' or btrim(coalesce(write_value->>'decision_text','')) = '' then
        raise exception 'Decision title and text are required.' using errcode = '22023';
      end if;
      insert into public.decisions(
        id, household_id, title, decision_text, owner_member_id, status,
        effective_at, source, confidence
      ) values (
        record_id_value, capture_row.household_id, title_value, btrim(write_value->>'decision_text'),
        owner_id_value, coalesce(nullif(write_value->>'status',''),'decided'),
        nullif(write_value->>'effective_at','')::timestamptz,
        coalesce(nullif(write_value->>'source',''),'pepper_capture'),
        coalesce(nullif(write_value->>'confidence','')::numeric, 1.000)
      );
      select to_jsonb(d) into after_value from public.decisions d where d.id = record_id_value;
      insert into public.state_changes(
        household_id, entity_type, entity_id, change_type, before_state, after_state,
        consequence_summary, confidence, source
      ) values (
        capture_row.household_id, 'decision', record_id_value::text, 'decision_created',
        null, after_value, 'A family decision was recorded.', 1.000, 'pepper_capture'
      );

    else
      raise exception 'Unsupported canonical operation: %.', coalesce(operation_value, '<missing>') using errcode = '22023';
    end if;

    change_value := pg_catalog.jsonb_build_object(
      'operation', operation_value,
      'entity_type', split_part(operation_value, '.', 1),
      'record_id', record_id_value
    );
    if write_value ? 'metadata' then
      if pg_catalog.jsonb_typeof(write_value->'metadata') <> 'object' then
        raise exception 'Write metadata must be an object.' using errcode = '22023';
      end if;
      if (write_value->'metadata') ?| array['operation','entity_type','record_id'] then
        raise exception 'Write metadata cannot replace canonical reference fields.' using errcode = '22023';
      end if;
      change_value := change_value || (write_value->'metadata');
    end if;
    changes_value := changes_value || pg_catalog.jsonb_build_array(change_value);
    refs_value := refs_value || pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_object(
      'entity_type', split_part(operation_value, '.', 1),
      'record_id', record_id_value
    ));
    destinations_value := pg_catalog.array_append(destinations_value, split_part(operation_value, '.', 1));

    if audit_event_type_value is not null then
      insert into public.audit_log(
        household_id, actor_member_id, capture_id, event_type, entity_type,
        entity_id, summary
      ) values (
        capture_row.household_id, actor_member_id_input, capture_id_input,
        audit_event_type_value, split_part(operation_value, '.', 1),
        record_id_value::text, audit_summary_value
      );
    end if;

    before_value := null;
    after_value := null;
  end loop;

  select coalesce(pg_catalog.jsonb_agg(ref order by ref->>'entity_type', ref->>'record_id'), '[]'::jsonb)
  into combined_refs_value
  from (
    select distinct ref
    from pg_catalog.jsonb_array_elements(coalesce(capture_row.aegis_record_ids, '[]'::jsonb) || refs_value) refs(ref)
  ) unique_refs;

  select pg_catalog.string_agg(destination, ',' order by destination)
  into destination_value
  from (select distinct unnest(destinations_value) as destination) destinations;

  if capture_row.aegis_destination is not null and capture_row.aegis_destination <> '' then
    select pg_catalog.string_agg(destination, ',' order by destination)
    into destination_value
    from (
      select distinct destination
      from unnest(
        pg_catalog.string_to_array(capture_row.aegis_destination, ',') ||
        coalesce(destinations_value, array[]::text[])
      ) destination
      where destination <> ''
    ) destinations;
  end if;

  sync_status_value := case
    when outcome_value = 'applied' and write_count = 0
      and pg_catalog.jsonb_array_length(existing_refs_value) = 0 then 'not_applicable'
    when outcome_value = 'applied' then 'synced'
    else 'needs_review'
  end;

  update public.captures c set
    status = outcome_value,
    extracted_facts = case
      when plan_kind_value = 'initial' then facts_value
      else coalesce(c.extracted_facts, '[]'::jsonb) || facts_value
    end,
    applied_changes = coalesce(c.applied_changes, '[]'::jsonb) || changes_value,
    remaining_ambiguities = ambiguities_value,
    aegis_sync_status = sync_status_value,
    aegis_last_attempt_at = now(),
    aegis_synced_at = case when sync_status_value in ('synced','not_applicable') then now() else null end,
    aegis_destination = destination_value,
    aegis_record_ids = combined_refs_value,
    aegis_sync_error = null,
    reconciled_by_member_id = actor_member_id_input,
    reconciled_at = now(),
    reconciliation_version = 1,
    updated_at = now()
  where c.id = capture_id_input;

  insert into public.audit_log(
    household_id, actor_member_id, capture_id, event_type, entity_type,
    entity_id, summary
  ) values (
    capture_row.household_id, actor_member_id_input, capture_id_input,
    case when outcome_value = 'needs_review' then 'capture_needs_review' else 'capture_reconciled' end,
    'capture', capture_id_input::text,
    write_count::text || ' canonical change(s) processed.'
  );

  result_value := pg_catalog.jsonb_build_object(
    'ok', true,
    'capture_id', capture_id_input,
    'status', outcome_value,
    'aegis_sync_status', sync_status_value,
    'applied_changes', changes_value,
    'remaining_ambiguities', ambiguities_value,
    'canonical_records', refs_value,
    'idempotent_replay', false
  );

  insert into private.capture_plan_applications(
    capture_id, household_id, actor_member_id, idempotency_key,
    plan_hash, plan_kind, outcome, result
  ) values (
    capture_id_input, capture_row.household_id, actor_member_id_input,
    btrim(idempotency_key_input), plan_hash_value, plan_kind_value,
    outcome_value, result_value
  );

  return result_value;
end;
$$;

revoke execute on function private.apply_capture_plan(uuid,uuid,text,jsonb) from public, anon, authenticated, service_role;
revoke execute on function private.pepper_assert_jsonb_keys(jsonb,text[],text) from public, anon, authenticated, service_role;
revoke execute on function private.pepper_assert_household_member(uuid,uuid,text) from public, anon, authenticated, service_role;

create or replace function private.pepper_record_capture_apply_failure(
  capture_id_input uuid,
  actor_member_id_input uuid,
  error_input text
)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  update public.captures c
  set aegis_sync_status = 'failed',
      aegis_last_attempt_at = now(),
      aegis_sync_error = left(coalesce(error_input, 'Capture plan failed.'), 1000),
      updated_at = now()
  where c.id = capture_id_input
    and c.member_id = actor_member_id_input
    and c.status in ('captured','partially_applied','needs_review');
  if not found then
    raise exception 'Capture not found or not retryable.' using errcode = '42501';
  end if;
end;
$$;
revoke execute on function private.pepper_record_capture_apply_failure(uuid,uuid,text) from public, anon, authenticated, service_role;

create or replace function private.list_capture_reviews(
  actor_member_id_input uuid,
  limit_input integer default 50
)
returns table (
  capture_id uuid,
  original_text text,
  source text,
  status text,
  reconciliation_status text,
  extracted_facts jsonb,
  applied_changes jsonb,
  remaining_ambiguities jsonb,
  canonical_records jsonb,
  captured_at timestamptz,
  updated_at timestamptz
)
language sql
security invoker
set search_path = ''
as $$
  select
    c.id, c.original_text, c.source, c.status, c.aegis_sync_status,
    c.extracted_facts, c.applied_changes, c.remaining_ambiguities,
    coalesce(c.aegis_record_ids, '[]'::jsonb), c.captured_at, c.updated_at
  from public.captures c
  where c.member_id = actor_member_id_input
    and c.status in ('captured','partially_applied','needs_review')
    and c.aegis_sync_status in ('needs_review','failed')
  order by c.captured_at desc
  limit least(greatest(coalesce(limit_input, 50), 1), 100)
$$;
revoke execute on function private.list_capture_reviews(uuid,integer) from public, anon, authenticated, service_role;

create or replace function private.resolve_capture_review(
  capture_id_input uuid,
  actor_member_id_input uuid,
  idempotency_key_input text,
  plan_input jsonb
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if plan_input->>'kind' <> 'review_resolution' then
    raise exception 'Review resolution requires a review_resolution plan.' using errcode = '22023';
  end if;
  return private.apply_capture_plan(capture_id_input, actor_member_id_input, idempotency_key_input, plan_input);
end;
$$;
revoke execute on function private.resolve_capture_review(uuid,uuid,text,jsonb) from public, anon, authenticated, service_role;

create or replace function private.pepper_record_ref_exists(
  household_id_input uuid,
  entity_type_input text,
  record_id_input uuid
)
returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
begin
  return case entity_type_input
    when 'task' then exists(select 1 from public.tasks t where t.id=record_id_input and t.household_id=household_id_input)
    when 'event' then exists(select 1 from public.events e where e.id=record_id_input and e.household_id=household_id_input)
    when 'grocery' then exists(select 1 from public.groceries g where g.id=record_id_input and g.household_id=household_id_input)
    when 'meal' then exists(select 1 from public.meal_plan m where m.id=record_id_input and m.household_id=household_id_input)
    when 'responsibility' then exists(select 1 from public.responsibilities r where r.id=record_id_input and r.household_id=household_id_input)
    when 'decision' then exists(select 1 from public.decisions d where d.id=record_id_input and d.household_id=household_id_input)
    else false
  end;
end;
$$;
revoke execute on function private.pepper_record_ref_exists(uuid,text,uuid) from public, anon, authenticated, service_role;

create or replace function private.capture_backlog_dry_run(
  expected_capture_ids_input uuid[],
  expected_capture_count_input integer,
  expected_record_refs_input jsonb
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  actual_capture_ids uuid[];
  actual_count integer;
  expected_count integer;
  ref_value jsonb;
  capture_id_value uuid;
  record_id_value uuid;
  entity_type_value text;
  household_id_value uuid;
  actual_refs jsonb;
  expected_refs jsonb;
begin
  if expected_capture_ids_input is null
     or expected_capture_count_input is null
     or expected_record_refs_input is null
     or pg_catalog.jsonb_typeof(expected_record_refs_input) <> 'array' then
    raise exception 'Expected capture IDs, count, and record references are required.' using errcode = '22023';
  end if;

  select coalesce(array_agg(c.id order by c.id), array[]::uuid[]), count(*)::integer
  into actual_capture_ids, actual_count
  from public.captures c
  where c.status <> 'dismissed'
    and c.aegis_sync_status in ('captured','needs_review','failed');

  select count(distinct id)::integer into expected_count
  from unnest(expected_capture_ids_input) ids(id);
  if expected_count <> cardinality(expected_capture_ids_input)
     or expected_capture_count_input <> expected_count
     or actual_count <> expected_capture_count_input
     or actual_capture_ids is distinct from (
       select coalesce(array_agg(id order by id), array[]::uuid[])
       from unnest(expected_capture_ids_input) ids(id)
     ) then
    raise exception 'Backlog capture IDs or count changed; regenerate the dry-run manifest.' using errcode = 'P0003';
  end if;

  for ref_value in select value from pg_catalog.jsonb_array_elements(expected_record_refs_input)
  loop
    perform private.pepper_assert_jsonb_keys(ref_value, array['capture_id','entity_type','record_id'], 'backlog record reference');
    capture_id_value := nullif(ref_value->>'capture_id','')::uuid;
    record_id_value := nullif(ref_value->>'record_id','')::uuid;
    entity_type_value := ref_value->>'entity_type';
    if capture_id_value is null or record_id_value is null
       or entity_type_value not in ('task','event','grocery','meal','responsibility','decision') then
      raise exception 'Unexpected backlog record reference.' using errcode = '22023';
    end if;
    select c.household_id into household_id_value
    from public.captures c
    where c.id = capture_id_value and c.id = any(expected_capture_ids_input);
    if not found
       or not private.pepper_record_ref_exists(household_id_value, entity_type_value, record_id_value) then
      raise exception 'Backlog record reference is missing or outside the capture household.' using errcode = 'P0003';
    end if;
  end loop;

  select coalesce(pg_catalog.jsonb_agg(ref order by ref::text), '[]'::jsonb)
  into expected_refs
  from (select distinct value as ref from pg_catalog.jsonb_array_elements(expected_record_refs_input)) refs;

  select coalesce(pg_catalog.jsonb_agg(ref order by ref::text), '[]'::jsonb)
  into actual_refs
  from (
    select distinct pg_catalog.jsonb_build_object(
      'capture_id', c.id,
      'entity_type', ref->>'entity_type',
      'record_id', ref->>'record_id'
    ) as ref
    from public.captures c
    cross join lateral pg_catalog.jsonb_array_elements(coalesce(c.aegis_record_ids, '[]'::jsonb)) refs(ref)
    where c.id = any(expected_capture_ids_input)
  ) refs;

  if actual_refs is distinct from expected_refs then
    raise exception 'Backlog canonical record references changed; regenerate the dry-run manifest.' using errcode = 'P0003';
  end if;

  return pg_catalog.jsonb_build_object(
    'ok', true,
    'dry_run', true,
    'capture_count', actual_count,
    'capture_ids', to_jsonb(actual_capture_ids),
    'record_refs', actual_refs,
    'writes_applied', 0
  );
end;
$$;
revoke execute on function private.capture_backlog_dry_run(uuid[],integer,jsonb) from public, anon, authenticated, service_role;

-- Keep the existing public capture helpers response-compatible while removing
-- pending and preventing non-transactional "applied" finalization.
create or replace function public.pepper_capture_input(
  session_token_input uuid,
  source_input text,
  original_text_input text,
  dedupe_key_input text default null
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  current_member uuid;
  current_household uuid;
  capture_id_value uuid;
  source_value text;
  original_text_value text;
  dedupe_key_value text;
  captured_at_value timestamptz;
begin
  current_member := private.pepper_set_session(session_token_input);
  current_household := private.pepper_current_household_id();
  perform private.pepper_touch_session(session_token_input);
  source_value := case lower(btrim(coalesce(source_input, 'text'))) when 'voice' then 'voice' else 'text' end;
  original_text_value := btrim(coalesce(original_text_input, ''));
  dedupe_key_value := left(nullif(btrim(coalesce(dedupe_key_input, '')), ''), 200);
  if original_text_value = '' or length(original_text_value) > 4000 then
    raise exception 'Tell Pepper something under 4,000 characters to save.' using errcode = '22023';
  end if;

  insert into public.captures(
    household_id, member_id, source, original_text, status, extracted_facts,
    applied_changes, dedupe_key, aegis_sync_status, sharing_scope
  ) values (
    current_household, current_member, source_value, original_text_value, 'captured',
    '[]'::jsonb, '[]'::jsonb, dedupe_key_value, 'captured', 'member_private'
  )
  on conflict (household_id, dedupe_key) where dedupe_key is not null do nothing
  returning id, captured_at into capture_id_value, captured_at_value;

  if capture_id_value is null and dedupe_key_value is not null then
    select c.id, c.captured_at into capture_id_value, captured_at_value
    from public.captures c
    where c.household_id=current_household and c.member_id=current_member and c.dedupe_key=dedupe_key_value;
  end if;
  if capture_id_value is null then raise exception 'Pepper could not preserve that note.' using errcode='P0001'; end if;
  return pg_catalog.jsonb_build_object(
    'ok',true,'capture_id',capture_id_value,'status','captured',
    'aegis_sync_status','captured','captured_at',captured_at_value
  );
end;
$$;

create or replace function public.pepper_finalize_capture(
  session_token_input uuid,
  capture_id_input uuid,
  status_input text,
  extracted_facts_input jsonb default '[]'::jsonb,
  applied_changes_input jsonb default '[]'::jsonb
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  current_member uuid;
  current_household uuid;
begin
  current_member := private.pepper_set_session(session_token_input);
  current_household := private.pepper_current_household_id();
  perform private.pepper_touch_session(session_token_input);
  if lower(btrim(coalesce(status_input,''))) <> 'needs_review'
     or pg_catalog.jsonb_typeof(coalesce(extracted_facts_input,'[]'::jsonb)) <> 'array'
     or pg_catalog.jsonb_typeof(coalesce(applied_changes_input,'[]'::jsonb)) <> 'array'
     or pg_catalog.jsonb_array_length(coalesce(applied_changes_input,'[]'::jsonb)) <> 0 then
    raise exception 'Canonical changes must be finalized through apply_capture_plan.' using errcode='22023';
  end if;
  update public.captures c set
    status='needs_review', extracted_facts=coalesce(extracted_facts_input,'[]'::jsonb),
    applied_changes='[]'::jsonb,
    remaining_ambiguities=case
      when pg_catalog.jsonb_array_length(coalesce(extracted_facts_input,'[]'::jsonb)) > 0
        then extracted_facts_input
      else pg_catalog.jsonb_build_array('Legacy capture requires review')
    end,
    aegis_sync_status='needs_review', aegis_last_attempt_at=now(), updated_at=now()
  where c.id=capture_id_input and c.household_id=current_household and c.member_id=current_member and c.status='captured';
  if not found then raise exception 'Capture not found or not permitted.' using errcode='42501'; end if;
  return pg_catalog.jsonb_build_object(
    'ok',true,'capture_id',capture_id_input,'status','needs_review','aegis_sync_status','needs_review'
  );
end;
$$;

drop policy if exists captures_member_insert on public.captures;
create policy captures_member_insert
on public.captures for insert to anon, authenticated
with check (
  household_id = (select private.pepper_current_household_id())
  and member_id = (select private.pepper_current_member_id())
  and source in ('voice','text')
  and status = 'captured'
  and aegis_sync_status = 'captured'
  and sharing_scope = 'member_private'
);

revoke execute on function public.pepper_capture_input(uuid,text,text,text) from public;
revoke execute on function public.pepper_finalize_capture(uuid,uuid,text,jsonb,jsonb) from public;
grant execute on function public.pepper_capture_input(uuid,text,text,text) to anon, authenticated;
grant execute on function public.pepper_finalize_capture(uuid,uuid,text,jsonb,jsonb) to anon, authenticated;

grant insert (
  household_id, member_id, source, original_text, status, extracted_facts,
  applied_changes, dedupe_key, aegis_sync_status, sharing_scope
) on public.captures to anon, authenticated;
grant update (
  status, extracted_facts, applied_changes, remaining_ambiguities,
  aegis_sync_status, aegis_last_attempt_at, updated_at
) on public.captures to anon, authenticated;

notify pgrst, 'reload schema';
